# Generated by Django 4.2 on 2023-08-12 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='group_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='teachers.studentgroup', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_schedules', to='students.schedule', verbose_name='Расписание'),
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='subject',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_schedules', to='teachers.subject', verbose_name='Предмет'),
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='time_lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_schedules', to='students.timelesson', verbose_name='Время урока'),
        ),
        migrations.AlterUniqueTogether(
            name='eventschedule',
            unique_together={('day', 'time_lesson', 'subject')},
        ),
    ]
