# Generated by Django 3.2.3 on 2021-06-07 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinetapp', '0002_studentgroup_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='group_student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='cabinetapp.studentgroup', verbose_name='Группа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.CreateModel(
            name='EventSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], max_length=1, verbose_name='День')),
                ('start_lesson', models.TimeField(verbose_name='Начало занятий')),
                ('end_lesson', models.TimeField(verbose_name='Окончание занятий')),
                ('comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='Комментарий')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_schedules', to='cabinetapp.schedule', verbose_name='Расписание')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_schedules', to='cabinetapp.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Урок расписаний',
                'verbose_name_plural': 'Уроки расписании',
            },
        ),
    ]
