# Generated by Django 3.2.3 on 2021-06-05 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinetapp', '0002_studentgroup_subjects'),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher', to='cabinetapp.subject', verbose_name='Предмет учителя'),
        ),
    ]
