# Generated by Django 3.2.3 on 2021-06-07 17:55

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_alter_user_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUser',
            fields=[
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('userapp.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=12, verbose_name='Телефон номер'),
        ),
    ]
